/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dll */

#ifndef _Included_Dll
#define _Included_Dll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dll
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dll_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Dll
 * Method:    dif
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dll_dif
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Dll
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dll_div
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Dll
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Dll_mul
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
